### ISSUE TITLE
没有show-models这个函数

### ISSUE THREAD

**Issue by demi0304** [ShixiangWang/ezcox#11]
install.packages("ezcox")#先安装包
packageVersion("ezcox")#0.4.0版本
library(survival)
library(ezcox)
library("devtools")
install.packages("devtools")
devtools::install_github("ShixiangWang/ezcox")
lung$ph.ecog <- factor(lung$ph.ecog)
zz <- ezcox(lung, covariates = c("sex", "ph.ecog"), controls = "age", return_models = TRUE)
zz
mds <- get_models(zz)
str(mds, max.level = 1)
install.packages("forestmodel")
library("forestmodel")
show_models(mds)
问题是没有show-models这个函数

**Comment by ShixiangWang** [comment]
你能否重启 R 会话，并运行下面的代码：

```r
library(ezcox)
library(survival)
zz <- ezcox(lung, covariates = c("sex", "ph.ecog"), controls = "age", return_models = TRUE)
mds <- get_models(zz)
show_models(mds)
```

另外能否告知下你的 R 版本？

**Comment by ShixiangWang** [comment]
你能否重启 R 会话，并运行下面的代码：

```r
library(ezcox)
library(survival)
zz <- ezcox(lung, covariates = c("sex", "ph.ecog"), controls = "age", return_models = TRUE)
mds <- get_models(zz)
show_models(mds)
```

另外能否告知下你的 R 版本？

**Comment by ShixiangWang** [comment]
另外，我应该有提示怎么安装 forstmodel 这个包

```
remotes::install_github("ShixiangWang/forestmodel")
```

**Comment by demi0304** [comment]
您好，非常感谢您在百忙之中抽出时间回复！我的R版本是3.6.2。昨天按照您的提示安装包，多次提示安装失败。忘了是在哪了看到安装forestmodel包，可以用 install.packages("forestmodel") 指令，链接到GitHub和这样直接安装有什么区别吗？今天再次按照您的提示安装包后，安装成功，现已经解决问题。再次感谢您的回复。

  

 ------------------&nbsp;原始邮件&nbsp;------------------
  发件人:&nbsp;"Shixiang Wang"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年4月20日(星期一) 中午11:09
 收件人:&nbsp;"ShixiangWang/ezcox"<ezcox@noreply.github.com&gt;;
 抄送:&nbsp;"钟丽丽"<1437832067@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [ShixiangWang/ezcox] 没有show-models这个函数 (#11)

 

 

 
另外，我应该有提示怎么安装 forstmodel 这个包
remotes::install_github("ShixiangWang/forestmodel")

**Comment by ShixiangWang** [comment]
直接安装是安装发布在 CRAN 上的版本，该包作者在接收我的更新代码后一直没有发布新版本到 CRAN，所以是没有办法使用的，必须安装我修改后的代码。
