### ISSUE TITLE
Fast way to add interaction terms?

### ISSUE THREAD

**Issue by lijing-lin** [ShixiangWang/ezcox#23]
Hi, just wondering how the the interaction terms can be handled as "controls" here. Any way to add them rather than manually  create new 'interaction variables' in the data? Cheers.

**Comment by ShixiangWang** [comment]
@lijing-lin Hi, lijing. Yeah, it is not supported currently. I will look into it and see if there is a fix.

**Comment by lijing-lin** [comment]
Cheers! That would be of great help.

**Comment by ShixiangWang** [comment]
Now controls with symbol `:*()|` will be used to auto-detect the interaction/combination term.

Could you install the latest GitHub version and see how it works?

```R
library(survival)
library(ezcox)

lung$ph.ecog <- factor(lung$ph.ecog)
ezcox(lung, covariates = c("age"), controls = "sex:ph.ecog")
ezcox(lung, covariates = c("age", "wt.loss"), controls = "sex:ph.ecog")

show_forest(lung, covariates = c("age", "wt.loss"), controls = "sex:ph.ecog")

lung2 <- lung
lung2$sex <- ifelse(lung2$sex == 1, "M", "F")
ezcox_group(lung2, grp_var = "sex", covariate = "ph.ecog", controls = "age : wt.loss")
```

**Comment by ShixiangWang** [comment]
Please note that to properly format the result table, 3 columns will be set to `NA`s.

![image](https://user-images.githubusercontent.com/25057508/138284415-1453ea3a-65e9-4a84-aeb3-4e2facee32bc.png)

**Comment by ShixiangWang** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [ezcox交互项问题和实现](https://trello.com/c/7O8tWKXm/18-ezcox%E4%BA%A4%E4%BA%92%E9%A1%B9%E9%97%AE%E9%A2%98%E5%92%8C%E5%AE%9E%E7%8E%B0)

**Comment by ShixiangWang** [comment]
@lijing-lin Hi, could this issue be fixed?

**Comment by lijing-lin** [comment]
@ShixiangWang  Cheers. I will give it go. Btw, the link above doesn't work.

**Comment by ShixiangWang** [comment]
@lijing-lin The link above is auto labeled by trello to track this issue in my plan. It's nothing with the issue itself, sorry for the bother :).

**Comment by lijing-lin** [comment]
> Could you install the latest GitHub version and see how it works?

Ok. I just got down to giving it try. The code 

> show_forest(lung, covariates = c("age"), controls = "sex : ph.ecog")

only gave the following

![image](https://user-images.githubusercontent.com/6393100/141154517-45955aef-81f4-4850-9640-fca526767e52.png)

**Comment by lijing-lin** [comment]
While these codes 
```
lung2 <- lung
lung2$sex <- ifelse(lung2$sex == 1, "M", "F")
ezcox_group(lung2, grp_var = "sex", covariate = "ph.ecog", controls = "age : wt.loss")

```
show

![image](https://user-images.githubusercontent.com/6393100/141154928-6c1f3cec-f76d-4b85-bd3f-5aa536ab2c4a.png)

Are they both supposed to be so?  I guess, my question is, where did the HR for interaction term go?

**Comment by ShixiangWang** [comment]
ezcox uses R package forestmodel to visualize the result models with forest plot. However, the forestmodel cannot support visualization of interaction term. I tried review and modify the source code and found that it is infeasible in current implementation.

You have to visualize the result by your own and maybe you can try the `forester()` provided by **ezcox**.

**Comment by lijing-lin** [comment]
Ok. I see. Thanks for the helps so far. Much appreciated.
