### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by qingjian1991** [ShixiangWang/ezcox#25]
诗翔：

我用你的这个R包，有两个建议，你可以改进一下：

1.  对covariates的顺序，按照用户给的顺序进行展示，现在是按照字符的大小排序的。
2. 对HR太大的值，使用科学记数法进行展示

这个是用的代码
```
zz = ezcox(
  scores.combined,
  covariates = c("JSI", "Tindex", "Subclonal_Aca", "Subclonal_Nec", "ITH_Aca", "ITH_Nec"),
  controls = "Age",
  time = "Survival_months",
  status = "Death",
  return_models = TRUE
)

mds = get_models(zz)

show_models(mds, drop_controls = TRUE)

```

这个是现在的图

![image](https://user-images.githubusercontent.com/19546092/152635665-f3eca2f9-63ee-4c84-a9b1-a629cf2e77ba.png)

**Comment by ShixiangWang** [comment]
@qingjian1991 青建师兄，你的第一个问题可以通过安装最新版的 https://github.com/ShixiangWang/forestmodel 包解决，我提交的新的代码用来保持输入的顺序。第2个跟科学计数法没有太大关系，默认都是保留2位小数。虽然同时控制科学计数法和小数点可以适当减少，但所占的位置还是蛮多的，不太通用。

```
> format(123456.789, scientific = T)
[1] "1.234568e+05"
> format(123456.789, scientific = T, digits = 2)
[1] "1.2e+05"
```

**Comment by ShixiangWang** [comment]
regport 用来开发替换这个包，有兴趣可以试一下 @qingjian1991 

https://shixiangwang.github.io/regport/reference/REGModelList.html
