### ISSUE TITLE
使用 meta 分析功能构建森林图！

### ISSUE THREAD

**Issue by ShixiangWang** [ShixiangWang/ezcox#8]
这样可以实现单变量生存分析的汇总以及多变量分析的分组分析

https://github.com/XSLiuLab/tumor-immunogenicity-score/blob/master/code/meta_analysis.R

**Comment by ShixiangWang** [comment]
https://github.com/NikNakk/forestmodel/

**Comment by ShixiangWang** [comment]
https://github.com/ShixiangWang/metawho

**Comment by demi0304** [comment]
install.packages("ezcox")#先安装包
packageVersion("ezcox")#0.4.0版本
library(survival)
library(ezcox)
library("devtools")
install.packages("devtools")
devtools::install_github("ShixiangWang/ezcox")
lung$ph.ecog <- factor(lung$ph.ecog)
zz <- ezcox(lung, covariates = c("sex", "ph.ecog"), controls = "age", return_models = TRUE)
zz
mds <- get_models(zz)
# 查看模型结构，其实是列表而已
str(mds, max.level = 1)
install.packages("forestmodel")
library("forestmodel")
show_models(mds)
问题是没有show-models这个函数
